exports.headers = {
	'Accept': '*/*',
	'Accept-Encoding': 'gzip, deflate, br',
	'Accept-Language': 'en-US,en;q=0.9',
	'Cache-Control': 'no-cache',
	'Content-Type': 'application/json',
	'Pragma': 'no-cache',
	'Referer': 'https://discord.com/channels/@me',
	'Sec-Ch-Ua': '" Not A;Brand"; v="99", "Google Chrome";v="97.0.4692.99"',
	'Sec-Ch-Ua-Mobile': '?0',
	'Sec-Ch-Ua-Platform': '"x64"',
	'Sec-Fetch-Dest': 'empty',
	'Sec-Fetch-Mode': 'cors',
	'Sec-Fetch-Site': 'same-orgin',
	'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36',
	'X-Debux-Options': 'bugReporterEnabled',
	'X-Discord-Locale': 'en-US',
	'Orgin': 'https://discord.com'
}

exports.v = '9';

exports.Events = {
	RATE_LIMIT: 'rateLimit',
	INVALID_REQUEST_WARNING: 'invalidRequestWarning',
	API_RESPONSE: 'apiResponse',
	API_REQUEST: 'apiRequest',
	CLIENT_READY: 'ready',
	/**
	 * @deprecated See {@link https://github.com/discord/discord-api-docs/issues/3690 this issue} for more information.
	 */
	APPLICATION_COMMAND_CREATE: 'applicationCommandCreate',
	/**
	 * @deprecated See {@link https://github.com/discord/discord-api-docs/issues/3690 this issue} for more information.
	 */
	APPLICATION_COMMAND_DELETE: 'applicationCommandDelete',
	/**
	 * @deprecated See {@link https://github.com/discord/discord-api-docs/issues/3690 this issue} for more information.
	 */
	APPLICATION_COMMAND_UPDATE: 'applicationCommandUpdate',
	GUILD_CREATE: 'guildCreate',
	GUILD_DELETE: 'guildDelete',
	GUILD_UPDATE: 'guildUpdate',
	GUILD_UNAVAILABLE: 'guildUnavailable',
	GUILD_MEMBER_ADD: 'guildMemberAdd',
	GUILD_MEMBER_REMOVE: 'guildMemberRemove',
	GUILD_MEMBER_UPDATE: 'guildMemberUpdate',
	GUILD_MEMBER_AVAILABLE: 'guildMemberAvailable',
	GUILD_MEMBERS_CHUNK: 'guildMembersChunk',
	GUILD_INTEGRATIONS_UPDATE: 'guildIntegrationsUpdate',
	GUILD_ROLE_CREATE: 'roleCreate',
	GUILD_ROLE_DELETE: 'roleDelete',
	INVITE_CREATE: 'inviteCreate',
	INVITE_DELETE: 'inviteDelete',
	GUILD_ROLE_UPDATE: 'roleUpdate',
	GUILD_EMOJI_CREATE: 'emojiCreate',
	GUILD_EMOJI_DELETE: 'emojiDelete',
	GUILD_EMOJI_UPDATE: 'emojiUpdate',
	GUILD_BAN_ADD: 'guildBanAdd',
	GUILD_BAN_REMOVE: 'guildBanRemove',
	CHANNEL_CREATE: 'channelCreate',
	CHANNEL_DELETE: 'channelDelete',
	CHANNEL_UPDATE: 'channelUpdate',
	CHANNEL_PINS_UPDATE: 'channelPinsUpdate',
	MESSAGE_CREATE: 'messageCreate',
	MESSAGE_DELETE: 'messageDelete',
	MESSAGE_UPDATE: 'messageUpdate',
	MESSAGE_BULK_DELETE: 'messageDeleteBulk',
	MESSAGE_REACTION_ADD: 'messageReactionAdd',
	MESSAGE_REACTION_REMOVE: 'messageReactionRemove',
	MESSAGE_REACTION_REMOVE_ALL: 'messageReactionRemoveAll',
	MESSAGE_REACTION_REMOVE_EMOJI: 'messageReactionRemoveEmoji',
	THREAD_CREATE: 'threadCreate',
	THREAD_DELETE: 'threadDelete',
	THREAD_UPDATE: 'threadUpdate',
	THREAD_LIST_SYNC: 'threadListSync',
	THREAD_MEMBER_UPDATE: 'threadMemberUpdate',
	THREAD_MEMBERS_UPDATE: 'threadMembersUpdate',
	USER_UPDATE: 'userUpdate',
	PRESENCE_UPDATE: 'presenceUpdate',
	RELATIONSHIP_ADD: 'relationshipAdd',
	VOICE_SERVER_UPDATE: 'voiceServerUpdate',
	VOICE_STATE_UPDATE: 'voiceStateUpdate',
	TYPING_START: 'typingStart',
	WEBHOOKS_UPDATE: 'webhookUpdate',
	INTERACTION_CREATE: 'interactionCreate',
	ERROR: 'error',
	WARN: 'warn',
	DEBUG: 'debug',
	CACHE_SWEEP: 'cacheSweep',
	SHARD_DISCONNECT: 'shardDisconnect',
	SHARD_ERROR: 'shardError',
	SHARD_RECONNECTING: 'shardReconnecting',
	SHARD_READY: 'shardReady',
	SHARD_RESUME: 'shardResume',
	INVALIDATED: 'invalidated',
	RAW: 'raw',
	STAGE_INSTANCE_CREATE: 'stageInstanceCreate',
	STAGE_INSTANCE_UPDATE: 'stageInstanceUpdate',
	STAGE_INSTANCE_DELETE: 'stageInstanceDelete',
	GUILD_STICKER_CREATE: 'stickerCreate',
	GUILD_STICKER_DELETE: 'stickerDelete',
	GUILD_STICKER_UPDATE: 'stickerUpdate',
	GUILD_SCHEDULED_EVENT_CREATE: 'guildScheduledEventCreate',
	GUILD_SCHEDULED_EVENT_UPDATE: 'guildScheduledEventUpdate',
	GUILD_SCHEDULED_EVENT_DELETE: 'guildScheduledEventDelete',
	GUILD_SCHEDULED_EVENT_USER_ADD: 'guildScheduledEventUserAdd',
	GUILD_SCHEDULED_EVENT_USER_REMOVE: 'guildScheduledEventUserRemove',
};

exports.ShardEvents = {
	CLOSE: 'close',
	DESTROYED: 'destroyed',
	INVALID_SESSION: 'invalidSession',
	READY: 'ready',
	RESUMED: 'resumed',
	ALL_READY: 'allReady',
};

exports.Status = {
	READY: 0,
	CONNECTING: 1,
	RECONNECTING: 2,
	IDLE: 3,
	NEARLY: 4,
	DISCONNECTED: 5,
	WAITING_FOR_GUILDS: 6,
	IDENTIFYING: 7,
	RESUMING: 8,
};

exports.WSCodes = {
	1000: 'WS_CLOSE_REQUESTED',
	4004: 'TOKEN_INVALID',
	4010: 'SHARDING_INVALID',
	4011: 'SHARDING_REQUIRED',
	4013: 'INVALID_INTENTS',
	4014: 'DISALLOWED_INTENTS',
};

exports.WSEvents = keyMirror([
	'READY',
	'RESUMED',
	'APPLICATION_COMMAND_CREATE',
	'APPLICATION_COMMAND_DELETE',
	'APPLICATION_COMMAND_UPDATE',
	'GUILD_CREATE',
	'GUILD_DELETE',
	'GUILD_UPDATE',
	'INVITE_CREATE',
	'INVITE_DELETE',
	'GUILD_MEMBER_ADD',
	'GUILD_MEMBER_REMOVE',
	'GUILD_MEMBER_UPDATE',
	'GUILD_MEMBERS_CHUNK',
	'GUILD_INTEGRATIONS_UPDATE',
	'GUILD_ROLE_CREATE',
	'GUILD_ROLE_DELETE',
	'GUILD_ROLE_UPDATE',
	'GUILD_BAN_ADD',
	'GUILD_BAN_REMOVE',
	'GUILD_EMOJIS_UPDATE',
	'CHANNEL_CREATE',
	'CHANNEL_DELETE',
	'CHANNEL_UPDATE',
	'CHANNEL_PINS_UPDATE',
	'MESSAGE_CREATE',
	'MESSAGE_DELETE',
	'MESSAGE_UPDATE',
	'MESSAGE_DELETE_BULK',
	'MESSAGE_REACTION_ADD',
	'MESSAGE_REACTION_REMOVE',
	'MESSAGE_REACTION_REMOVE_ALL',
	'MESSAGE_REACTION_REMOVE_EMOJI',
	'THREAD_CREATE',
	'THREAD_UPDATE',
	'THREAD_DELETE',
	'THREAD_LIST_SYNC',
	'THREAD_MEMBER_UPDATE',
	'THREAD_MEMBERS_UPDATE',
	'USER_UPDATE',
	'PRESENCE_UPDATE',
	'RELATIONSHIP_ADD',
	'TYPING_START',
	'VOICE_STATE_UPDATE',
	'VOICE_SERVER_UPDATE',
	'WEBHOOKS_UPDATE',
	'INTERACTION_CREATE',
	'STAGE_INSTANCE_CREATE',
	'STAGE_INSTANCE_UPDATE',
	'STAGE_INSTANCE_DELETE',
	'GUILD_STICKERS_UPDATE',
	'GUILD_SCHEDULED_EVENT_CREATE',
	'GUILD_SCHEDULED_EVENT_UPDATE',
	'GUILD_SCHEDULED_EVENT_DELETE',
	'GUILD_SCHEDULED_EVENT_USER_ADD',
	'GUILD_SCHEDULED_EVENT_USER_REMOVE',
]);

exports.Opcodes = {
	DISPATCH: 0,
	HEARTBEAT: 1,
	IDENTIFY: 2,
	STATUS_UPDATE: 3,
	VOICE_STATE_UPDATE: 4,
	VOICE_GUILD_PING: 5,
	RESUME: 6,
	RECONNECT: 7,
	REQUEST_GUILD_MEMBERS: 8,
	INVALID_SESSION: 9,
	HELLO: 10,
	HEARTBEAT_ACK: 11,
};


function keyMirror(arr) {
	let tmp = Object.create(null);
	for (const value of arr) tmp[value] = value;
	return tmp;
}